# Generated by Django 4.2.2 on 2023-07-09 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0003_remove_user_is_customer_user_is_artisan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='artisan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artisans.artisans'),
        ),
    ]
