# Generated by Django 3.2 on 2023-04-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_artisan',
        ),
    ]
