# Generated by Django 4.2.2 on 2023-07-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0006_orderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='', upload_to='artisans/images/products'),
        ),
    ]
