# Generated by Django 4.2.2 on 2023-07-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0007_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisans',
            name='dp',
            field=models.ImageField(default='', upload_to='artisans/images/dp'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dp',
            field=models.ImageField(default='', upload_to='customer/images/dp'),
        ),
    ]
