# Generated by Django 4.2.2 on 2023-07-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0008_alter_artisans_dp_alter_customer_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
